apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: hello-version
  namespace: test
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    hello-versionVersion: extensions/v1beta1
    kind: Deployment
    name: hello-version
  targetCPUUtilizationPercentage: 50
status:
  currentReplicas: 0
  desiredReplicas: 0