apiVersion: apps/v1
kind: Deployment
metadata: 
  name: hello-version
  namespace: test
  labels:
     app: hello-version
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: hello-version
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
      labels:
        app: hello-version
    spec:
      containers:
        - name: hello-version
          image: nitikornchumnankul/api-test-version:v3.1 
          imagePullPolicy: IfNotPresent
          ports: 
            - name: http
              containerPort: 8080
              protocol: TCP
      livenessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:9898/healthz
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:9898/readyz
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi
