apiVersion: apps/v1
kind: Deployment
metadata: 
  name: hello-version
  namespace: test
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      run: hello-version
  template:
    metadata:
      labels:
        run: hello-version
    spec:
      containers:
        - name: hello-version
          image: nitikornchumnankul/api-test-version:v1 
          imagePullPolicy: IfNotPresent
          ports: 
            - name: http
              containerPort: 8080
              protocol: TCP
