apiVersion: apps/v1
kind: Deployment
metadata: 
  name: hello-version
  labels:
    app: hello-version
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-version
      version: v1
  template:
    metadata:
      labels:
        app: hello-version
        version: v1
    spec:
      containers:
        - name: hello-version
          image: nitikornchumnankul/api-test-version:v1 
          imagePullPolicy: IfNotPresent
          ports: 
            - name: http
              containerPort: 8080
              protocol: TCP
