hello-versionVersion: v1
kind: Service
metadata:
  name: hello-version
  namespace: istio-system
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
  selector:
    run: hello-version