apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
    name: hello-version
    namespace: test
spec:
    hosts:
      - "hello-version.kongtelalug.test"
    gateways:
      - public-gateway.test.svc.cluster.local
    http:
      - route:
           - destination:
                 host: hello-version